# Generated by Django 4.1.3 on 2022-12-03 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_courses_rename_if_deleted_news_is_deleted_lesson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteachers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='courseteachers',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='courseteachers',
            name='updated_at',
        ),
    ]
