# Generated by Django 4.1.3 on 2022-12-03 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_courseteachers_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='news',
            name='is_deleted',
        ),
    ]
