# Generated by Django 4.1.3 on 2022-12-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_courses_is_deleted_remove_lesson_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseteachers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
