# Generated by Django 4.1.3 on 2022-12-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_courses_options_coursefeedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='CourseTeachers',
            new_name='CourseTeacher',
        ),
    ]
